### ISSUE TITLE
Wrong picture

### ISSUE THREAD

**Issue by AlexisJAnderson** [The-Scratching-Post/Famility-Tree#1]

**Comment by Swoofie** [comment]
I cant believe the wrong document was uploaded, this could of been devastating for our organization if Alexis didnt spot it

**Comment by Nanabell** [comment]
@AlexisJAnderson thanks for spotting this!
Since you are responsible for providing the Famility Tree images i'll assign this task to you 😉

**Comment by AlexisJAnderson** [comment]
Thank you boss, I got on it straight away. My push is ready and awaiting review.

**Comment by AlexisJAnderson** [comment]
Branches merged.
